env: standard
runtime: nodejs10

handlers:
  - url: /static/js/(.*)
    static_files: build/static/js/\1
    upload: build/static/js/(.*)

  - url: /static/css/(.*)
    static_files: build/static/css/\1
    upload: build/static/css/(.*)

  - url: /static/media/(.*)
    static_files: build/static/media/\1
    upload: build/static/media/(.*)

  - url: /(.*\.(json|ico))$
    static_files: build/\1
    upload: build/.*\.(json|ico)$

  - url: /
    static_files: build/index.html
    upload: build/index.html

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
######### optional gae flex config (run from build folder) ########
# runtime: nodejs
# env: flex
#
# config optimized for demo for cost savings (not production)
# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
# memory_gb: 0.5
# disk_size_gb: 10
