name: GitHub Pages

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - main
            - dev

env:
    SKIP_PREFLIGHT_CHECK: true

jobs:
    deploy:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependencies
              run: yarn install

            - name: Check for linting errors
              run: yarn test

            - name: Build production website
              run: yarn storybook:build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./storybook-static
