# This is a basic workflow to help you get started with Actions

name: test

on: 
  workflow_dispatch:
    inputs:
      manual_deploy:
        description: "Manual Deploy"
        required: true
        type: boolean
        default: true

jobs:
  print-tag:
    runs-on: ubuntu-latest
#     if:  ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.manual_deploy == 'test_workflow_input' }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo "Deploying to production server on branch $GITHUB_REF"
